# TEMPORARY SCRIPT
# WILL MOVE AND MAKE IT MORE SOPHISTICATED LATER
# BUT RIGHT NOW I WANT A SINGLE SCRIPT FOR QUICK DEBUGGING AND EDITING.
# LATER ON, WILL ADD LATENT SPACE and ATTENTION.
# CREATED YYYY-MM-DD.

